//! The built-in categories and their pattern groups (design §11.15).
//!
//! Ported from geld (<https://github.com/brandonmcconnell/geld>) at commit
//! `5b8ce0e470fcd2b2538da6c700d7d96197f57de3`, `packages/core/src/categories.ts`
//! and `test-patterns.ts`: MIT License, Copyright (c) 2026 Brandon McConnell
//! (credited in `NOTICE`). The pattern lists and nouns are geld's, with these
//! changes only:
//!
//! - `dist/`, `build/` and `out/` move from `generated-code` into a new
//!   Generated group, `build-output` (off by default, OQ-46), and
//!   `generated-code`'s title drops "& build output";
//! - titles, icons and Agent config's chip nouns follow design §11.15
//!   (`Stories & fixtures`, Lucide icon names, "agent file(s)");
//! - Generated is on by default (geld: off);
//! - geld's change-kind categories ("trivial", "large") and group
//!   descriptions are left out.

use super::BuiltinCategory;

/// A named list of patterns inside a built-in category.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PatternGroup {
    /// The key settings use in `disabled_groups` (`"unit"`).
    pub key: &'static str,
    pub title: &'static str,
    pub patterns: &'static [&'static str],
}

/// A built-in category: its settings key, display strings and groups.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BuiltinDef {
    pub id: BuiltinCategory,
    pub key: &'static str,
    pub title: &'static str,
    /// Label noun for one file ("test file").
    pub noun: &'static str,
    pub noun_plural: &'static str,
    /// Chip noun for one file ("test").
    pub chip: &'static str,
    pub chip_plural: &'static str,
    /// A Lucide icon name (`assets/icons/<icon>.svg`).
    pub icon: &'static str,
    pub default_enabled: bool,
    pub default_disabled_groups: &'static [&'static str],
    pub groups: &'static [PatternGroup],
}

/// geld's `CODE_EXTENSIONS`: `*.spec.*` and friends only for code, since
/// OpenAPI documents are often named `api.spec.yaml`.
macro_rules! code_extensions {
    () => {
        "{js,jsx,ts,tsx,mjs,cjs,mts,cts,vue,svelte,astro,py,rb,php,dart,kt,kts,swift,scala,sc,ex,exs,lua,cs,fs,fsx,go,rs,java,groovy,clj,cljs,cljc,coffee,res,ml,re,hs,zig,nim,jl,r,R,m,mm,sh,bash,zsh,ps1,sql,elm,gleam,erl,pl,pm,c,cc,cpp,cxx,h,hpp,cu}"
    };
}

const TESTS: &[PatternGroup] = &[
    PatternGroup {
        key: "unit",
        title: "Unit & integration tests",
        patterns: &[
            "*.test.*",
            "*.tests.*",
            concat!("*.spec.", code_extensions!()),
            concat!("*.specs.", code_extensions!()),
            concat!("*.unit.", code_extensions!()),
            concat!("*.integration.", code_extensions!()),
            "*_test.*",
            "*_tests.*",
            concat!("*_spec.", code_extensions!()),
            "test_*.*",
            "tests_*.*",
            "*Test.{java,kt,kts,scala,groovy,php,cs,swift,dart}",
            "*Tests.{java,kt,kts,scala,groovy,php,cs,swift,dart}",
            "*TestCase.{java,kt,php,py,cs,swift}",
            "*Spec.{java,kt,kts,scala,groovy,js,ts}",
            "*IT.java",
            "*.bats",
            "*.robot",
            "*.feature",
        ],
    },
    PatternGroup {
        key: "e2e",
        title: "End-to-end tests",
        patterns: &[
            "*.e2e.*",
            "*.e2e-spec.*",
            "*.e2e-test.*",
            "*.cy.*",
            "*.pw.*",
            "e2e/",
            "e2e-tests/",
            "e2e_tests/",
            "cypress/",
            "playwright/",
            "playwright-report/",
            "test-results/",
            "integration-tests/",
            "integration_tests/",
            "acceptance/",
            "acceptance-tests/",
            "acceptance_tests/",
        ],
    },
    PatternGroup {
        key: "directories",
        title: "Test directories",
        patterns: &[
            "test/",
            "tests/",
            "__tests__/",
            "__test__/",
            "spec/",
            "specs/",
            "__specs__/",
            "__spec__/",
            "__mocks__/",
            "testing/",
            "testdata/",
            "test-data/",
            "test_data/",
            "test-utils/",
            "test_utils/",
            "testutils/",
            "test-helpers/",
            "test_helpers/",
            "testhelpers/",
            "unit-tests/",
            "unit_tests/",
            "Tests/",
            "*.Tests/",
            "*.Test/",
            "*.UnitTests/",
            "*.IntegrationTests/",
            "*Tests/",
            "androidTest/",
            "androidTestDebug/",
            "testFixtures/",
            "coverage/",
            ".nyc_output/",
            "htmlcov/",
        ],
    },
    PatternGroup {
        key: "snapshots",
        title: "Snapshots & recordings",
        patterns: &[
            "*.snap",
            "*.snap.*",
            "__snapshots__/",
            "__image_snapshots__/",
            "*-snapshots/",
            "__cassettes__/",
            "cassettes/",
            "vcr_cassettes/",
            "__recordings__/",
        ],
    },
    PatternGroup {
        key: "tooling",
        title: "Test tooling & configuration",
        patterns: &[
            "jest.config.*",
            "jest.setup.*",
            "jest-setup.*",
            "jest.preset.*",
            "jest.*.config.*",
            "vitest.config.*",
            "vitest.setup.*",
            "vitest.workspace.*",
            "vitest.*.config.*",
            "playwright.config.*",
            "playwright.*.config.*",
            "cypress.config.*",
            "cypress.json",
            "cypress.env.json",
            "karma.conf.*",
            ".mocharc*",
            "mocha.opts",
            "wdio.conf.*",
            "wdio.*.conf.*",
            "protractor.conf.*",
            "nightwatch.conf.*",
            "nightwatch.json",
            "codecept.conf.*",
            "ava.config.*",
            "jasmine.json",
            "testem.js",
            ".testem.json",
            "setupTests.*",
            "setup-tests.*",
            "setup_tests.*",
            "test-setup.*",
            "test_setup.*",
            "testSetup.*",
            "pytest.ini",
            "conftest.py",
            "tox.ini",
            ".coveragerc",
            "codecov.yml",
            ".codecov.yml",
            ".nycrc",
            ".nycrc.*",
            "phpunit.xml",
            "phpunit.xml.dist",
            "phpunit.dist.xml",
            ".rspec",
            "spec_helper.rb",
            "rails_helper.rb",
            "test_helper.rb",
            "*.runsettings",
            ".testcaferc.*",
            "stryker.conf.*",
            "stryker.config.*",
        ],
    },
];

const GENERATED: &[PatternGroup] = &[
    PatternGroup {
        key: "lockfiles",
        title: "Lockfiles",
        patterns: &[
            "package-lock.json",
            "npm-shrinkwrap.json",
            "pnpm-lock.yaml",
            "yarn.lock",
            "bun.lock",
            "bun.lockb",
            "deno.lock",
            "Cargo.lock",
            "Gemfile.lock",
            "poetry.lock",
            "Pipfile.lock",
            "uv.lock",
            "pdm.lock",
            "composer.lock",
            "go.sum",
            "mix.lock",
            "pubspec.lock",
            "Podfile.lock",
            "Package.resolved",
            "packages.lock.json",
            "flake.lock",
            "gradle.lockfile",
        ],
    },
    PatternGroup {
        key: "generated-code",
        title: "Generated code",
        patterns: &[
            "*.generated.*",
            "*.gen.*",
            "*.g.dart",
            "*.freezed.dart",
            "*.pb.go",
            "*.pb.*",
            "*_pb2.py",
            "*_pb2_grpc.py",
            "*.pb.cc",
            "*.pb.h",
            "*.min.js",
            "*.min.css",
            "*.map",
            "*.bundle.js",
            "*.d.ts.map",
            "__generated__/",
            "generated/",
            ".generated/",
            "*.snap.js",
            "schema.graphql.json",
            "graphql.schema.json",
            "*.tsbuildinfo",
        ],
    },
    PatternGroup {
        key: "build-output",
        title: "Build output",
        patterns: &["dist/", "build/", "out/"],
    },
];

const VENDORED: &[PatternGroup] = &[PatternGroup {
    key: "vendored",
    title: "Vendored directories",
    patterns: &[
        "vendor/",
        "vendors/",
        "node_modules/",
        "third_party/",
        "third-party/",
        "thirdparty/",
        "Pods/",
        "Carthage/",
        "bower_components/",
        "jspm_packages/",
        ".yarn/",
    ],
}];

const AGENTS: &[PatternGroup] = &[PatternGroup {
    key: "agents",
    title: "AI agent files",
    patterns: &[
        ".cursor/",
        ".cursorrules",
        ".cursorignore",
        ".cursorindexingignore",
        "CLAUDE.md",
        "CLAUDE.local.md",
        ".claude/",
        "AGENTS.md",
        "AGENT.md",
        "GEMINI.md",
        ".gemini/",
        ".codex/",
        ".windsurfrules",
        ".windsurf/",
        ".clinerules",
        ".clinerules/",
        ".roo/",
        ".roomodes",
        ".aider*",
        ".github/copilot-instructions.md",
        ".github/instructions/",
        ".github/prompts/",
        ".continue/",
        ".junie/",
        ".kiro/",
        ".mcp.json",
        "mcp.json",
        "llms.txt",
        "llms-full.txt",
    ],
}];

const DOCS: &[PatternGroup] = &[PatternGroup {
    key: "docs",
    title: "Documentation",
    patterns: &[
        "*.md",
        "*.mdx",
        "*.markdown",
        "*.rst",
        "*.adoc",
        "*.txt",
        "docs/",
        "doc/",
        "CHANGELOG*",
        "CHANGES*",
        "HISTORY*",
        "RELEASE_NOTES*",
        ".changeset/",
        ".changes/",
        "LICENSE*",
        "LICENCE*",
        "NOTICE*",
        "AUTHORS*",
        "CONTRIBUTORS*",
    ],
}];

const TOOLING: &[PatternGroup] = &[
    PatternGroup {
        key: "ci",
        title: "CI & automation",
        patterns: &[
            ".github/workflows/",
            ".github/actions/",
            ".github/dependabot.yml",
            ".github/renovate.json*",
            "renovate.json*",
            ".renovaterc*",
            ".gitlab-ci.yml",
            ".circleci/",
            ".travis.yml",
            "azure-pipelines*.yml",
            "Jenkinsfile*",
            "bitbucket-pipelines.yml",
            ".buildkite/",
            "cloudbuild.yaml",
            ".drone.yml",
            "appveyor.yml",
            "codecov.yml",
            ".codecov.yml",
            ".pre-commit-config.yaml",
            ".husky/",
            "lefthook.yml",
            "CODEOWNERS",
            ".github/CODEOWNERS",
            ".github/ISSUE_TEMPLATE/",
            ".github/PULL_REQUEST_TEMPLATE*",
            ".github/FUNDING.yml",
        ],
    },
    PatternGroup {
        key: "lint-format",
        title: "Linters, formatters & editor config",
        patterns: &[
            ".eslintrc*",
            "eslint.config.*",
            ".eslintignore",
            ".prettierrc*",
            "prettier.config.*",
            ".prettierignore",
            "biome.json*",
            ".stylelintrc*",
            "stylelint.config.*",
            ".editorconfig",
            ".oxlintrc*",
            "oxlint.config.*",
            ".markdownlint*",
            "cspell.*",
            ".cspell*",
            ".commitlintrc*",
            "commitlint.config.*",
            ".npmrc",
            ".nvmrc",
            ".node-version",
            ".tool-versions",
            ".ruby-version",
            ".python-version",
            "mise.toml",
            ".mise.toml",
            ".gitattributes",
            ".gitignore",
            ".dockerignore",
            ".vscode/",
            ".idea/",
            ".devcontainer/",
        ],
    },
    PatternGroup {
        key: "build-config",
        title: "Build & compiler configuration",
        patterns: &[
            "tsconfig*.json",
            "jsconfig*.json",
            "babel.config.*",
            ".babelrc*",
            "webpack.config.*",
            "webpack.*.js",
            "rollup.config.*",
            "vite.config.*",
            "rolldown.config.*",
            "rspack.config.*",
            "esbuild.config.*",
            "tsup.config.*",
            "tsdown.config.*",
            "turbo.json",
            "nx.json",
            "lerna.json",
            "pnpm-workspace.yaml",
            ".swcrc",
            "postcss.config.*",
            "tailwind.config.*",
            "Dockerfile*",
            "docker-compose*.yml",
            "docker-compose*.yaml",
            "compose.yml",
            "compose.yaml",
            "Makefile",
            "Procfile",
            "netlify.toml",
            "vercel.json",
            "wrangler.toml",
            "fly.toml",
            "app.yaml",
            "nixpacks.toml",
            "Taskfile.yml",
            "justfile",
        ],
    },
];

const STORIES: &[PatternGroup] = &[
    PatternGroup {
        key: "stories",
        title: "Storybook stories",
        patterns: &[
            "*.stories.*",
            "*.story.*",
            ".storybook/",
            "__stories__/",
            "stories/",
        ],
    },
    PatternGroup {
        key: "fixtures",
        title: "Fixtures & mock data",
        patterns: &[
            "__fixtures__/",
            "fixtures/",
            "fixture/",
            "__mocks__/",
            "mocks/",
            "__data__/",
            "testdata/",
            "seeds/",
            "seed/",
        ],
    },
    PatternGroup {
        key: "i18n",
        title: "Translations",
        patterns: &[
            "locales/",
            "locale/",
            "i18n/",
            "translations/",
            "lang/",
            "*.po",
            "*.pot",
            "*.mo",
            "*.xlf",
            "*.xliff",
            "*.arb",
            "*.strings",
            "*.stringsdict",
            "messages.*.xlf",
            "intl/",
        ],
    },
];

/// The built-in categories in match order, indexed by [`BuiltinCategory`].
pub static BUILTINS: [BuiltinDef; 7] = [
    BuiltinDef {
        id: BuiltinCategory::Tests,
        key: "tests",
        title: "Tests",
        noun: "test file",
        noun_plural: "test files",
        chip: "test",
        chip_plural: "tests",
        icon: "flask-conical",
        default_enabled: true,
        default_disabled_groups: &[],
        groups: TESTS,
    },
    BuiltinDef {
        id: BuiltinCategory::Generated,
        key: "generated",
        title: "Generated",
        noun: "generated file",
        noun_plural: "generated files",
        chip: "generated",
        chip_plural: "generated",
        icon: "file-cog",
        default_enabled: true,
        default_disabled_groups: &["build-output"],
        groups: GENERATED,
    },
    BuiltinDef {
        id: BuiltinCategory::Vendored,
        key: "vendored",
        title: "Vendored",
        noun: "vendored file",
        noun_plural: "vendored files",
        chip: "vendored",
        chip_plural: "vendored",
        icon: "package",
        default_enabled: false,
        default_disabled_groups: &[],
        groups: VENDORED,
    },
    BuiltinDef {
        id: BuiltinCategory::Agents,
        key: "agents",
        title: "Agent config",
        noun: "agent config file",
        noun_plural: "agent config files",
        chip: "agent file",
        chip_plural: "agent files",
        icon: "bot",
        default_enabled: false,
        default_disabled_groups: &[],
        groups: AGENTS,
    },
    BuiltinDef {
        id: BuiltinCategory::Docs,
        key: "docs",
        title: "Docs",
        noun: "documentation file",
        noun_plural: "documentation files",
        chip: "doc",
        chip_plural: "docs",
        icon: "book-open",
        default_enabled: false,
        default_disabled_groups: &[],
        groups: DOCS,
    },
    BuiltinDef {
        id: BuiltinCategory::Tooling,
        key: "tooling",
        title: "Tooling & CI",
        noun: "tooling file",
        noun_plural: "tooling files",
        chip: "tooling",
        chip_plural: "tooling",
        icon: "wrench",
        default_enabled: false,
        default_disabled_groups: &[],
        groups: TOOLING,
    },
    BuiltinDef {
        id: BuiltinCategory::Stories,
        key: "stories",
        title: "Stories & fixtures",
        noun: "story or fixture file",
        noun_plural: "stories, fixtures & i18n files",
        chip: "fixture",
        chip_plural: "fixtures",
        icon: "layers",
        default_enabled: false,
        default_disabled_groups: &[],
        groups: STORIES,
    },
];
