// Perf corpora generators and manifest (plan T2.1, design §12.2).
import { afterAll, describe, expect, test } from "bun:test";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { syntheticPlan } from "../../benches/corpora/make-synthetic";
import { makeSandbox } from "../support/sandbox";

const repoRoot = resolve(import.meta.dir, "../..");
const sandbox = makeSandbox();
afterAll(() => sandbox.cleanup());

type Entry = {
  name: string;
  repo: string;
  base: string;
  head: string;
  mode: string;
};

let counter = 0;
/** A fresh, not yet existing corpora root inside the sandbox. */
function freshRoot(): string {
  return join(sandbox.home, "corpora", String(counter++));
}

function run(
  argv: string[],
  env: Record<string, string>,
): { code: number | null; stdout: string; stderr: string } {
  const r = Bun.spawnSync(argv, { cwd: repoRoot, env });
  return {
    code: r.exitCode,
    stdout: r.stdout.toString(),
    stderr: r.stderr.toString(),
  };
}

function withRoot(
  root: string,
  extra: Record<string, string> = {},
): Record<string, string> {
  return { ...sandbox.env, POLYGLOSS_CORPORA: root, ...extra };
}

/** Runs a generator and returns the entry it printed. */
function generate(script: string, root: string, args: string[] = []): Entry {
  const r = run(["bun", `benches/corpora/${script}`, ...args], withRoot(root));
  expect({ script, stderr: r.stderr, code: r.code }).toEqual({
    script,
    stderr: "",
    code: 0,
  });
  return JSON.parse(r.stdout) as Entry;
}

/** git in `repo` only: discovery never climbs above it. */
function git(repo: string, args: string[]): string {
  // No background `git maintenance` after a commit: its objects/maintenance.lock
  // would come and go between two fingerprints of a repo (seen on CI).
  const r = Bun.spawnSync(
    ["git", "-C", repo, "-c", "maintenance.auto=false", ...args],
    { env: { ...sandbox.env, GIT_CEILING_DIRECTORIES: dirname(repo) } },
  );
  if (r.exitCode !== 0)
    throw new Error(`git ${args.join(" ")}: ${r.stderr.toString()}`);
  return r.stdout.toString();
}

function objectIds(e: Entry): string[] {
  return git(e.repo, [
    "rev-parse",
    `${e.base}^{tree}`,
    `${e.head}^{tree}`,
    `${e.base}^{commit}`,
    `${e.head}^{commit}`,
  ])
    .trim()
    .split("\n");
}

type Stat = { path: string; added: number | null; deleted: number | null };

/** `git diff --numstat` with the app's rename flags; binaries have nulls. */
function numstat(e: Entry): Stat[] {
  const out = git(e.repo, [
    "diff",
    "--numstat",
    "-z",
    "-M50%",
    "-l1000",
    e.base,
    e.head,
  ]);
  const stats: Stat[] = [];
  const parts = out.split("\0");
  for (let i = 0; i < parts.length; i++) {
    const head = parts[i];
    if (!head) continue;
    const [a, d, path] = head.split("\t");
    const num = (s: string | undefined) =>
      s === "-" || s === undefined ? null : Number(s);
    if (path === "") {
      // rename: `a\td\t\0old\0new`
      stats.push({ path: parts[i + 2] ?? "", added: num(a), deleted: num(d) });
      i += 2;
    } else {
      stats.push({ path: path ?? "", added: num(a), deleted: num(d) });
    }
  }
  return stats;
}

function statuses(e: Entry): string[] {
  return git(e.repo, [
    "diff",
    "--name-status",
    "-M50%",
    "-l1000",
    e.base,
    e.head,
  ])
    .trim()
    .split("\n")
    .map((l) => (l[0] === "R" ? "R" : (l[0] ?? "")));
}

function changedLines(stats: Stat[]): number {
  return stats.reduce((n, s) => n + (s.added ?? 0) + (s.deleted ?? 0), 0);
}

/** The generated lockfiles the core classifies as generated by name. */
const lockfile =
  /(^|\/)(Cargo\.lock|package-lock\.json|yarn\.lock|pnpm-lock\.yaml|go\.sum)$/;

function extension(path: string): string {
  const name = path.split("/").pop() ?? "";
  return name.includes(".") ? (name.split(".").pop() ?? "") : name;
}

describe("generated corpora", () => {
  test("typical corpus is deterministic", () => {
    const rootA = freshRoot();
    const rootB = freshRoot();
    const a = generate("make-typical.ts", rootA);
    const b = generate("make-typical.ts", rootB);
    expect(a).toEqual({
      name: "typical",
      repo: join(rootA, "generated", "typical"),
      base: "corpus-base",
      head: "corpus-head",
      mode: "three-dot",
    });
    expect(objectIds(a)).toEqual(objectIds(b));
    // Regenerating over its own output replaces it with identical objects.
    const again = generate("make-typical.ts", rootA);
    expect(objectIds(again)).toEqual(objectIds(a));
  });

  test("typical corpus looks like an agent PR", () => {
    const e = generate("make-typical.ts", freshRoot());
    const stats = numstat(e);
    expect(stats.length).toBeGreaterThanOrEqual(28);
    expect(stats.length).toBeLessThanOrEqual(32);
    const changed = changedLines(stats);
    expect(changed).toBeGreaterThanOrEqual(1_800);
    expect(changed).toBeLessThanOrEqual(2_200);
    const kinds = statuses(e);
    for (const k of ["A", "M", "D"]) expect(kinds).toContain(k);
    expect(kinds.filter((k) => k === "R")).toHaveLength(1);
    const binaries = stats.filter((s) => s.added === null);
    expect(binaries).toHaveLength(1);
    const exts = new Set(
      stats.filter((s) => s.added !== null).map((s) => extension(s.path)),
    );
    expect([...exts].sort()).toEqual(["go", "md", "rs", "ts"]);
    // The working tree is checked out at the head, like a real clone.
    expect(git(e.repo, ["status", "--porcelain"])).toBe("");
  });

  test("synthetic generator honors --scale", () => {
    const root = freshRoot();
    const e = generate("make-synthetic.ts", root, ["--scale", "0.01"]);
    expect(e).toEqual({
      name: "synthetic",
      repo: join(root, "generated", "synthetic-scale-0.01"),
      base: "corpus-base",
      head: "corpus-head",
      mode: "three-dot",
    });
    const stats = numstat(e);
    expect(stats).toHaveLength(20);
    const changed = changedLines(stats);
    expect(changed).toBeGreaterThanOrEqual(4_500);
    expect(changed).toBeLessThanOrEqual(5_500);
    expect(statuses(e)).toContain("R");
    expect(stats.some((s) => lockfile.test(s.path))).toBe(true);
    expect(new Set(stats.map((s) => extension(s.path))).size).toBeGreaterThan(
      12,
    );
    // Same scale, same objects.
    const again = generate("make-synthetic.ts", freshRoot(), [
      "--scale",
      "0.01",
    ]);
    expect(objectIds(again)).toEqual(objectIds(e));
  });

  test("synthetic plan at full scale matches design §12.2", () => {
    const plan = syntheticPlan(1);
    expect(plan.files).toBe(2_000);
    expect(plan.changedLines).toBe(500_000);
    expect(plan.languages).toBe(30);
    expect(plan.renames).toBe(100);
    expect(plan.lockfiles).toBeGreaterThanOrEqual(3);
    expect(plan.lockfiles).toBeLessThanOrEqual(10);
    expect(syntheticPlan(0.01).files).toBe(20);
  });

  test("synthetic corpus at full scale has 2,000 files and ~500k diff lines", () => {
    const e = generate("make-synthetic.ts", freshRoot());
    expect(e.repo.endsWith("/generated/synthetic")).toBe(true);
    const stats = numstat(e);
    expect(stats).toHaveLength(2_000);
    const changed = changedLines(stats);
    expect(changed).toBeGreaterThanOrEqual(475_000);
    expect(changed).toBeLessThanOrEqual(525_000);
    const kinds = statuses(e);
    expect(kinds.filter((k) => k === "R")).toHaveLength(100);
    const locks = stats.filter((s) => lockfile.test(s.path));
    expect(locks).toHaveLength(5);
    const code = stats.filter((s) => !lockfile.test(s.path));
    expect(new Set(code.map((s) => extension(s.path))).size).toBe(30);
  }, 120_000);

  test("synthetic rejects a bad --scale", () => {
    for (const bad of ["0", "-1", "abc", "2"]) {
      const r = run(
        ["bun", "benches/corpora/make-synthetic.ts", "--scale", bad],
        withRoot(freshRoot()),
      );
      expect({ bad, code: r.code }).toEqual({ bad, code: 2 });
      expect(r.stderr).toContain("--scale");
    }
  });

  test("huge-file corpus is one 200k-line file with about 100 hunks", () => {
    const e = generate("make-huge-file.ts", freshRoot());
    expect(e.name).toBe("huge-file");
    const stats = numstat(e);
    expect(stats).toHaveLength(1);
    const path = stats[0]?.path ?? "";
    const base = git(e.repo, ["cat-file", "blob", `${e.base}:${path}`]);
    expect(base.split("\n").length - 1).toBe(200_000);
    const hunks = git(e.repo, ["diff", "-U3", e.base, e.head])
      .split("\n")
      .filter((l) => l.startsWith("@@ ")).length;
    expect(hunks).toBeGreaterThanOrEqual(95);
    expect(hunks).toBeLessThanOrEqual(105);
  });

  test("a generator refuses to replace a directory it did not create", () => {
    const root = freshRoot();
    const foreign = join(root, "generated", "typical");
    mkdirSync(foreign, { recursive: true });
    writeFileSync(join(foreign, "keep.txt"), "mine\n");
    const r = run(["bun", "benches/corpora/make-typical.ts"], withRoot(root));
    expect(r.code).toBe(2);
    expect(r.stderr).toContain("refusing");
    expect(readdirSync(foreign)).toEqual(["keep.txt"]);
    // Nothing half-built is left next to it.
    expect(readdirSync(join(root, "generated"))).toEqual(["typical"]);
  });
});

describe("benches/corpora/manifest.ts", () => {
  test("manifest lists four corpora", () => {
    const root = freshRoot();
    const r = run(["bun", "benches/corpora/manifest.ts"], withRoot(root));
    expect(r.stderr).toBe("");
    expect(r.code).toBe(0);
    expect(JSON.parse(r.stdout)).toEqual([
      {
        name: "typical",
        repo: join(root, "generated", "typical"),
        base: "corpus-base",
        head: "corpus-head",
        mode: "three-dot",
      },
      {
        name: "synthetic",
        repo: join(root, "generated", "synthetic"),
        base: "corpus-base",
        head: "corpus-head",
        mode: "three-dot",
      },
      {
        name: "huge-file",
        repo: join(root, "generated", "huge-file"),
        base: "corpus-base",
        head: "corpus-head",
        mode: "three-dot",
      },
      {
        name: "linux",
        repo: join(root, "linux"),
        base: "v6.10",
        head: "v6.11",
        mode: "direct",
      },
    ]);
    // Nothing is created just by listing.
    expect(existsSync(root)).toBe(false);
  });

  test("POLYGLOSS_LINUX_REPO points the linux entry at an existing clone", () => {
    const linux = join(sandbox.home, "elsewhere", "linux");
    const r = run(
      ["bun", "benches/corpora/manifest.ts", "--corpus", "linux"],
      withRoot(freshRoot(), { POLYGLOSS_LINUX_REPO: linux }),
    );
    expect(r.code).toBe(0);
    expect(JSON.parse(r.stdout)).toEqual({
      name: "linux",
      repo: linux,
      base: "v6.10",
      head: "v6.11",
      mode: "direct",
    });
  });

  test("the default root is polygloss-corpora next to the main checkout", () => {
    const common = Bun.spawnSync(
      ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
      { cwd: repoRoot, env: sandbox.env },
    )
      .stdout.toString()
      .trim();
    const expected = join(dirname(dirname(common)), "polygloss-corpora");
    // The sandbox env has no POLYGLOSS_CORPORA or POLYGLOSS_LINUX_REPO.
    const r = run(["bun", "benches/corpora/manifest.ts"], sandbox.env);
    expect(r.code).toBe(0);
    const entries = JSON.parse(r.stdout) as Entry[];
    expect(entries.map((e) => relative(expected, e.repo))).toEqual([
      "generated/typical",
      "generated/synthetic",
      "generated/huge-file",
      "linux",
    ]);
  });

  test("--check fails for a missing corpus and passes once it exists", () => {
    const root = freshRoot();
    const check = () =>
      run(
        [
          "bun",
          "benches/corpora/manifest.ts",
          "--corpus",
          "typical",
          "--check",
        ],
        withRoot(root),
      );
    const missing = check();
    expect(missing.code).toBe(1);
    expect(missing.stderr).toContain("make-typical.ts");
    generate("make-typical.ts", root);
    const ok = check();
    expect(ok.stderr).toBe("");
    expect(ok.code).toBe(0);
    expect((JSON.parse(ok.stdout) as Entry).name).toBe("typical");
  });

  test("rejects an unknown corpus", () => {
    const r = run(
      ["bun", "benches/corpora/manifest.ts", "--corpus", "nope"],
      withRoot(freshRoot()),
    );
    expect(r.code).toBe(2);
    expect(r.stderr).toContain("nope");
  });
});

describe("benches/corpora/fetch-linux.sh", () => {
  // A stand-in for the kernel: three commits, annotated tags on the last two,
  // so a depth-1 fetch of both tags leaves a shallow repo.
  function upstream(): string {
    const dir = join(sandbox.home, `upstream-${counter++}`);
    mkdirSync(dir, { recursive: true });
    const g = (args: string[]) => git(dir, args);
    g(["init", "-q", "--initial-branch=master"]);
    for (const [i, tag] of [
      [1, null],
      [2, "v6.10"],
      [3, "v6.11"],
    ] as const) {
      writeFileSync(join(dir, "Makefile"), `VERSION = 6\nPATCHLEVEL = ${i}\n`);
      g(["add", "Makefile"]);
      g(["commit", "-q", "-m", `release ${i}`]);
      if (tag) g(["tag", "-a", "-m", `Linux ${tag}`, tag]);
    }
    return dir;
  }

  function fetchLinux(
    env: Record<string, string>,
    args: string[] = [],
  ): ReturnType<typeof run> {
    return run(["benches/corpora/fetch-linux.sh", ...args], env);
  }

  /** Every file under `.git` with its size and mtime, plus all refs. */
  function fingerprint(repo: string): string[] {
    const out: string[] = [];
    const walk = (dir: string) => {
      for (const name of readdirSync(dir).sort()) {
        const p = join(dir, name);
        const s = statSync(p);
        if (s.isDirectory()) walk(p);
        else out.push(`${relative(repo, p)} ${s.size} ${s.mtimeMs}`);
      }
    };
    walk(join(repo, ".git"));
    return [...out, git(repo, ["for-each-ref"])];
  }

  test("fetches v6.10 and v6.11 shallowly into a new repo", () => {
    const root = freshRoot();
    const src = upstream();
    const r = fetchLinux(
      withRoot(root, { POLYGLOSS_LINUX_URL: `file://${src}` }),
    );
    expect(r.code).toBe(0);
    const e = JSON.parse(r.stdout) as Entry;
    expect(e).toEqual({
      name: "linux",
      repo: join(root, "linux"),
      base: "v6.10",
      head: "v6.11",
      mode: "direct",
    });
    expect(objectIds(e)).toEqual(objectIds({ ...e, repo: src }));
    expect(git(e.repo, ["rev-parse", "--is-shallow-repository"]).trim()).toBe(
      "true",
    );
    expect(git(e.repo, ["rev-list", "--count", "v6.10"]).trim()).toBe("1");
    // Same answer as the manifest.
    const m = run(
      ["bun", "benches/corpora/manifest.ts", "--corpus", "linux", "--check"],
      withRoot(root),
    );
    expect(m.code).toBe(0);
    expect(JSON.parse(m.stdout)).toEqual(e);
  });

  test("reuses a repo that has both tags without writing to it", () => {
    const src = upstream();
    const before = fingerprint(src);
    const r = fetchLinux(
      withRoot(freshRoot(), {
        POLYGLOSS_LINUX_REPO: src,
        // Any fetch attempt would fail.
        POLYGLOSS_LINUX_URL: `file://${join(sandbox.home, "no-such-repo")}`,
      }),
    );
    expect(r.stderr).toBe("");
    expect(r.code).toBe(0);
    expect((JSON.parse(r.stdout) as Entry).repo).toBe(src);
    expect(fingerprint(src)).toEqual(before);
  });

  test("refuses to modify a repo that lacks the tags", () => {
    const repo = join(sandbox.home, `other-${counter++}`);
    mkdirSync(repo, { recursive: true });
    git(repo, ["init", "-q", "--initial-branch=main"]);
    writeFileSync(join(repo, "a.txt"), "a\n");
    git(repo, ["add", "a.txt"]);
    git(repo, ["commit", "-q", "-m", "mine"]);
    const before = fingerprint(repo);
    const r = fetchLinux(
      withRoot(freshRoot(), {
        POLYGLOSS_LINUX_REPO: repo,
        POLYGLOSS_LINUX_URL: `file://${upstream()}`,
      }),
    );
    expect(r.code).toBe(1);
    expect(r.stdout).toBe("");
    expect(r.stderr).toContain("refusing");
    expect(fingerprint(repo)).toEqual(before);
  });

  test("--dry-run resolves the same repo as the manifest and touches nothing", () => {
    // The sandbox env has neither variable: both fall back to the default root.
    for (const env of [
      sandbox.env,
      withRoot(freshRoot()),
      withRoot(freshRoot(), {
        POLYGLOSS_LINUX_REPO: join(sandbox.home, "x", "linux"),
      }),
    ]) {
      const dry = fetchLinux(env, ["--dry-run"]);
      expect(dry.stderr).toBe("");
      expect(dry.code).toBe(0);
      const m = run(
        ["bun", "benches/corpora/manifest.ts", "--corpus", "linux"],
        env,
      );
      expect(JSON.parse(dry.stdout)).toEqual(JSON.parse(m.stdout));
    }
    expect(existsSync(join(sandbox.home, "x"))).toBe(false);
  });
});
